-- =============================================================
-- V1.0__Init.sql - Criação das tabelas do projeto pw45s
-- =============================================================

-- tb_authority
CREATE TABLE tb_authority (
                              id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              authority VARCHAR(50) NOT NULL UNIQUE,
                              PRIMARY KEY (id)
);

-- tb_user
CREATE TABLE tb_user (
                         id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         username     VARCHAR(50)  NOT NULL UNIQUE,
                         display_name VARCHAR(255) NOT NULL,
                         password     VARCHAR(255) NOT NULL,
                         email        VARCHAR(255) NOT NULL UNIQUE,
                         active       BOOLEAN      NOT NULL DEFAULT FALSE,
                         PRIMARY KEY (id)
);

-- tb_user_authorities
CREATE TABLE tb_user_authorities (
                                     user_id      BIGINT NOT NULL,
                                     authority_id BIGINT NOT NULL,
                                     PRIMARY KEY (user_id, authority_id),
                                     CONSTRAINT FK_UserAuthorities_User
                                         FOREIGN KEY (user_id) REFERENCES tb_user (id),
                                     CONSTRAINT FK_UserAuthorities_Authority
                                         FOREIGN KEY (authority_id) REFERENCES tb_authority (id)
);

-- tb_address
CREATE TABLE tb_address (
                            id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            street   VARCHAR(255),
                            number   VARCHAR(255),
                            city     VARCHAR(255),
                            state    VARCHAR(255),
                            zip_code VARCHAR(255),
                            country  VARCHAR(255),
                            user_id  BIGINT,
                            PRIMARY KEY (id),
                            CONSTRAINT FK_Address_User
                                FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

-- tb_category
CREATE TABLE tb_category (
                             id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             name VARCHAR(255),
                             PRIMARY KEY (id)
);

-- tb_product
CREATE TABLE tb_product (
                            id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            name         VARCHAR(255)   NOT NULL,
                            description  VARCHAR(1024),
                            price        NUMERIC(19, 2) NOT NULL,
                            url_imagem   VARCHAR(255),
                            image_name   VARCHAR(100),
                            content_type VARCHAR(50),
                            category_id  BIGINT,
                            PRIMARY KEY (id),
                            CONSTRAINT FK_Product_Category
                                FOREIGN KEY (category_id) REFERENCES tb_category (id)
);

-- tb_order
CREATE TABLE tb_order (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          order_date     TIMESTAMP,
                          status         VARCHAR(50),
                          total          NUMERIC(19, 2),
                          payment_method VARCHAR(50),
                          shipping_cost  NUMERIC(10, 2),
                          shipping_type  VARCHAR(20),
                          user_id        BIGINT,
                          address_id     BIGINT,
                          PRIMARY KEY (id),
                          CONSTRAINT FK_Order_User
                              FOREIGN KEY (user_id) REFERENCES tb_user (id),
                          CONSTRAINT FK_Order_Address
                              FOREIGN KEY (address_id) REFERENCES tb_address (id)
);

-- tb_order_item
CREATE TABLE tb_order_item (
                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               order_index INTEGER,
                               quantity    INTEGER,
                               price       NUMERIC(19, 2),
                               order_id    BIGINT,
                               product_id  BIGINT,
                               PRIMARY KEY (id),
                               CONSTRAINT FK_OrderItem_Order
                                   FOREIGN KEY (order_id) REFERENCES tb_order (id),
                               CONSTRAINT FK_OrderItem_Product
                                   FOREIGN KEY (product_id) REFERENCES tb_product (id)
);

-- tb_order_status_history
CREATE TABLE tb_order_status_history (
                                         id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                         previous_status VARCHAR(50),
                                         new_status      VARCHAR(50) NOT NULL,
                                         changed_at      TIMESTAMP   NOT NULL,
                                         observation     VARCHAR(255),
                                         order_id        BIGINT      NOT NULL,
                                         changed_by      BIGINT,
                                         PRIMARY KEY (id),
                                         CONSTRAINT FK_StatusHistory_Order
                                             FOREIGN KEY (order_id) REFERENCES tb_order (id),
                                         CONSTRAINT FK_StatusHistory_User
                                             FOREIGN KEY (changed_by) REFERENCES tb_user (id)
);

-- tb_order_attachment
CREATE TABLE tb_order_attachment (
                                     id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     original_file_name VARCHAR(255) NOT NULL,
                                     stored_file_name   VARCHAR(255) NOT NULL,
                                     content_type       VARCHAR(255) NOT NULL,
                                     file_size          BIGINT,
                                     uploaded_at        TIMESTAMP    NOT NULL,
                                     description        VARCHAR(255),
                                     order_id           BIGINT       NOT NULL,
                                     uploaded_by        BIGINT,
                                     PRIMARY KEY (id),
                                     CONSTRAINT FK_Attachment_Order
                                         FOREIGN KEY (order_id) REFERENCES tb_order (id),
                                     CONSTRAINT FK_Attachment_User
                                         FOREIGN KEY (uploaded_by) REFERENCES tb_user (id)
);